### ISSUE TITLE
Prompts and evaluation code.

### ISSUE THREAD

**Issue by m-zhirnov** [Kevin-thu/DiffMorpher#28]
Hi!

Could you please share with us the prompts (for the evaluation dataset) and evaluation code used to compute the **PPL**, **PDV** and **FID** metrics? During testing, I noticed that the direct use of LPIPS (perceptual loss) leads to results that do not match those in **Table 1** of your paper.

This would help us a lot to ensure consistency in our comparison.

**Comment by Kevin-thu** [comment]
I have sent you an email. Thanks.

**Comment by zimingzhong** [comment]
> I have sent you an email. Thanks.

I've been doing some research on this recently, and I also want a copy of the test code because my implementation results are orders of magnitude different from PPL PDV in table1. zhongzm@shanghaitech.edu.cn

**Comment by momoddup** [comment]
> I have sent you an email. Thanks.

I've been researching this recently and would really appreciate it if you could share a copy of the test code and prompts. Thanks!
my email is 2558201377@qq.com

**Comment by jpsml** [comment]
Hi, would you please also share with me the evaluation code for computing the PPL, PDV, and FID metrics? My e-mail is joao.mlima@impa.br.

**Comment by willyawan16** [comment]
> I have sent you an email. Thanks.


Hi, would you also please to share the evaluation code with me for computing the PPL, PDV, and the FID metrics? My email is willyawan31@gmail.com

**Comment by rpdahxn** [comment]
Hi!
Would it be possible to get the evaluation code as well? I’d like to test it too.
My email: rpekgus@cau.ac.kr
Thanks!

**Comment by qingpingmo** [comment]
Hello, could you please also provide me with the evaluation code? I would like to run tests as well.

**Comment by Kevin-thu** [comment]
> Hello, could you please also provide me with the evaluation code? I would like to run tests as well.

Please send me an email.

**Comment by young91319** [comment]
Hi, would you please also share with me the prompts you use for the MorphBench dataset?

My email is young91319@gmail.com

Thanks!
