### ISSUE TITLE
click train loraA occurred an error

### ISSUE THREAD

**Issue by ifredom** [Kevin-thu/DiffMorpher#4]
platform: windows 10
conda python: 3.10.13
pip: pip 23.1.2
Nvidia: 3060 12G
![image](https://github.com/Kevin-thu/DiffMorpher/assets/13759936/512cfe0f-e31a-410f-989f-83c1c97cd066)

**Comment by Kevin-thu** [comment]
Hi, this is actually a warning and not an error, you can just ignore it and wait for LoRA training.

**Comment by ifredom** [comment]
I updated the picture of the error report. The operation procedure is as follows: after clone and install, when the default target and source images are used, the training button is directly clicked, and this error occurs.

**Comment by Kevin-thu** [comment]
The key issue is here:
![image](https://github.com/Kevin-thu/DiffMorpher/assets/97650565/3fe33d88-1ea5-44a9-b5a9-40f6f14108a8)
Try the following first:
https://stackoverflow.com/questions/57814535/assertionerror-torch-not-compiled-with-cuda-enabled-in-spite-upgrading-to-cud
https://blog.csdn.net/m0_74890428/article/details/130184164
